# Generated by Django 4.2.1 on 2023-05-19 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emre_world', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
        migrations.RemoveField(
            model_name='article',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='article',
            name='page',
            field=models.CharField(choices=[('about', 'About'), ('reims', 'Reims'), ('metallurgie', 'Metallurgie'), ('entreprise', 'Entreprise')], default='about', max_length=200),
        ),
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='default-slug', unique=True),
        ),
    ]
