# Generated by Django 4.2.1 on 2023-05-22 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emre_world', '0002_remove_article_image_remove_article_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='subtitle', unique=True),
        ),
    ]
