# Generated by Django 4.2.1 on 2023-05-22 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emre_world', '0003_article_image_alter_article_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='slug',
            new_name='subtitle',
        ),
    ]
