# Generated by Django 4.2.1 on 2023-05-23 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emre_world', '0004_rename_slug_article_subtitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
    ]
