# Generated by Django 4.2.1 on 2023-05-23 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emre_world', '0009_article_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='page',
            field=models.CharField(choices=[('about', 'About'), ('reims', 'Reims'), ('metallurgie', 'Metallurgie'), ('entreprise', 'Entreprise')], default='about', max_length=1000),
        ),
    ]
